<?php

declare(strict_types=1);

namespace GustavoQueiroz\HyperfCrudGeneratorTest\Integration;

use GustavoQueiroz\HyperfCrudGenerator\Schema\QueryExecutor;
use GustavoQueiroz\HyperfCrudGenerator\Schema\SchemaInspector;
use GustavoQueiroz\HyperfCrudGenerator\Schema\Table;
use GustavoQueiroz\HyperfCrudGenerator\Generator\CrudGenerator;
use GustavoQueiroz\HyperfCrudGenerator\Generator\GeneratorContext;
use GustavoQueiroz\HyperfCrudGenerator\Support\FileWriter;
use GustavoQueiroz\HyperfCrudGenerator\Support\StubRenderer;
use Hyperf\Context\ApplicationContext;
use Hyperf\Database\ConnectionResolver;
use Hyperf\Database\ConnectionResolverInterface;
use Psr\Container\ContainerInterface;
use Psr\EventDispatcher\EventDispatcherInterface;
use PDO;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/** Requires disposable test databases. Creates only randomly named fixture tables. */
final class CatalogIntegrationTest extends TestCase
{
    public static function drivers(): array
    {
        return [['mysql', 'MYSQL'], ['mariadb', 'MARIADB'], ['pgsql', 'PGSQL'], ['sqlsrv', 'SQLSRV']];
    }

    #[DataProvider('drivers')]
    public function testRealCatalog(string $driver, string $prefix): void
    {
        $dsn = getenv('CRUD_TEST_' . $prefix . '_DSN');
        if (! $dsn) {
            self::markTestSkipped('Set CRUD_TEST_' . $prefix . '_DSN to run against a disposable database.');
        }
        $pdo = new PDO($dsn, getenv('CRUD_TEST_' . $prefix . '_USER') ?: '', getenv('CRUD_TEST_' . $prefix . '_PASSWORD') ?: '', [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        ]);
        $schema = getenv('CRUD_TEST_' . $prefix . '_SCHEMA') ?: match ($driver) {
            'pgsql' => 'public', 'sqlsrv' => 'dbo', default => $pdo->query('SELECT DATABASE()')->fetchColumn(),
        };
        $name = 'crud_fixture_' . bin2hex(random_bytes(4));
        $parent = $name . '_parent';
        $quote = static fn ($value) => match ($driver) {
            'mysql', 'mariadb' => chr(96) . str_replace(chr(96), chr(96) . chr(96), $value) . chr(96),
            'sqlsrv' => '[' . str_replace(']', ']]', $value) . ']',
            default => '"' . str_replace('"', '""', $value) . '"',
        };
        $qualified = $quote($schema) . '.' . $quote($name);
        $parentQualified = $quote($schema) . '.' . $quote($parent);
        $identity = match ($driver) {
            'pgsql' => 'BIGINT GENERATED BY DEFAULT AS IDENTITY',
            'sqlsrv' => 'BIGINT IDENTITY(2147483648,1)',
            default => 'BIGINT AUTO_INCREMENT',
        };
        $parentKey = $driver === 'sqlsrv' ? 'BIGINT IDENTITY(9000000000,1)' : 'BIGINT';
        $pdo->exec("CREATE TABLE $parentQualified (id $parentKey PRIMARY KEY)");
        try {
            $pdo->exec("CREATE TABLE $qualified (id $identity PRIMARY KEY, email VARCHAR(120) NOT NULL UNIQUE, parent_id BIGINT NULL, amount DECIMAL(12,2) NOT NULL DEFAULT 0 CHECK (amount >= 0), FOREIGN KEY (parent_id) REFERENCES $parentQualified (id) ON DELETE SET NULL)");
            try {
                if ($driver === 'sqlsrv') {
                    $trigger = $quote($schema) . '.' . $quote($name . '_trigger');
                    $pdo->exec("CREATE TRIGGER $trigger ON $qualified AFTER INSERT AS INSERT INTO $parentQualified DEFAULT VALUES");
                }
                $executor = new class($pdo) implements QueryExecutor {
                    public function __construct(private PDO $pdo) {}
                    public function select(string $connection, string $sql, array $bindings = []): array
                    {
                        $statement = $this->pdo->prepare($sql);
                        $statement->execute($bindings);
                        return $statement->fetchAll(PDO::FETCH_ASSOC);
                    }
                };
                $inspector = new SchemaInspector($executor);
                self::assertContains($name, $inspector->tables('test', $driver, $schema));
                $table = $inspector->inspect($name, 'test', $driver, $schema);
                self::assertSame('id', $table->key()->name);
                self::assertTrue($table->key()->identity);
                self::assertSame(120, $table->column('email')->length);
                self::assertSame('decimal:2', $table->column('amount')->cast());
                self::assertContains(['email'], $table->uniqueKeys);
                self::assertSame(['parent_id'], $table->foreignKeys[0]['columns']);
                self::assertSame($parent, $table->foreignKeys[0]['table']);
                self::assertSame('SET NULL', $table->foreignKeys[0]['on_delete']);
                self::assertNotEmpty($table->checks);
                $this->exerciseGeneratedRepository($pdo, $driver, $table);
            } finally {
                $pdo->exec("DROP TABLE $qualified");
            }
        } finally {
            $pdo->exec("DROP TABLE $parentQualified");
        }
    }

    private function exerciseGeneratedRepository(PDO $pdo, string $driver, Table $table): void
    {
        $connectionClass = match ($driver) {
            'pgsql' => \Hyperf\Database\PgSQL\PostgreSqlConnection::class,
            'sqlsrv' => \Hyperf\Database\Sqlsrv\SqlServerConnection::class,
            default => \Hyperf\Database\MySqlConnection::class,
        };
        $connection = new $connectionClass($pdo, $table->schema, '', ['driver' => $driver, 'name' => 'test', 'odbc' => $driver === 'sqlsrv']);
        $resolver = new ConnectionResolver(['test' => $connection]);
        $dispatcher = new class implements EventDispatcherInterface {
            public function dispatch(object $event): object { return $event; }
        };
        $container = new class($resolver, $dispatcher) implements ContainerInterface {
            public function __construct(private $resolver, private $dispatcher) {}
            public function has(string $id): bool { return in_array($id, [ConnectionResolverInterface::class, EventDispatcherInterface::class], true); }
            public function get(string $id): mixed
            {
                return match ($id) {
                    ConnectionResolverInterface::class => $this->resolver,
                    EventDispatcherInterface::class => $this->dispatcher,
                    default => throw new \RuntimeException('Unexpected container entry: ' . $id),
                };
            }
            public function make(string $name, array $parameters): mixed
            {
                if ($name === \Hyperf\Contract\LengthAwarePaginatorInterface::class) {
                    return new \Hyperf\Paginator\LengthAwarePaginator(...$parameters);
                }
                throw new \RuntimeException('Unexpected factory: ' . $name);
            }
        };
        ApplicationContext::setContainer($container);
        $namespace = 'Real' . ucfirst($driver);
        $root = sys_get_temp_dir() . '/hyperf-crud-real-' . bin2hex(random_bytes(8));
        $context = new GeneratorContext('RecordItem', $table->schema . '.' . $table->name, $namespace, "$root/app",
            "$root/config/routes.php", "$root/docs", "$root/test", schema: $table, connection: 'test', testNamespace: $namespace . '\\Tests');
        (new CrudGenerator(new StubRenderer(), new FileWriter()))->generate($context, ['integration_test']);
        $loader = static function (string $class) use ($root, $namespace): void {
            if (str_starts_with($class, $namespace . '\\')) {
                $relative = substr($class, strlen($namespace) + 1);
                $path = str_starts_with($relative, 'Tests\\')
                    ? $root . '/test/' . substr($relative, 6) . '.php'
                    : $root . '/app/' . str_replace('\\', '/', $relative) . '.php';
                if (is_file($path)) {
                    require $path;
                }
            }
        };
        spl_autoload_register($loader);
        $oldFlag = getenv('CRUD_INTEGRATION_TESTS');
        putenv('CRUD_INTEGRATION_TESTS=1');
        try {
            $testClass = $namespace . '\\Tests\\RecordItemRepositoryIntegrationTest';
            $test = new $testClass('testRepositoryCrudWithinTransaction');
            $test->testRepositoryCrudWithinTransaction();
            // Re-running proves the generated transaction test cleans up its rows.
            $test->testRepositoryCrudWithinTransaction();
            self::assertSame(0, $connection->table($context->table)->count());
        } finally {
            putenv($oldFlag === false ? 'CRUD_INTEGRATION_TESTS' : 'CRUD_INTEGRATION_TESTS=' . $oldFlag);
            spl_autoload_unregister($loader);
            $iterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($root, \FilesystemIterator::SKIP_DOTS), \RecursiveIteratorIterator::CHILD_FIRST);
            foreach ($iterator as $file) {
                $file->isDir() ? rmdir($file->getPathname()) : unlink($file->getPathname());
            }
            rmdir($root);
        }
    }
}
