<?php

declare(strict_types=1);

namespace GustavoQueiroz\HyperfCrudGeneratorTest\Integration;

use GustavoQueiroz\HyperfCrudGenerator\Schema\QueryExecutor;
use GustavoQueiroz\HyperfCrudGenerator\Schema\SchemaInspector;
use PDO;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/** Requires disposable test databases. Creates only randomly named fixture tables. */
final class CatalogIntegrationTest extends TestCase
{
    public static function drivers(): array
    {
        return [['mysql', 'MYSQL'], ['mariadb', 'MARIADB'], ['pgsql', 'PGSQL'], ['sqlsrv', 'SQLSRV']];
    }

    #[DataProvider('drivers')]
    public function testRealCatalog(string $driver, string $prefix): void
    {
        $dsn = getenv('CRUD_TEST_' . $prefix . '_DSN');
        if (! $dsn) {
            self::markTestSkipped('Set CRUD_TEST_' . $prefix . '_DSN to run against a disposable database.');
        }
        $pdo = new PDO($dsn, getenv('CRUD_TEST_' . $prefix . '_USER') ?: '', getenv('CRUD_TEST_' . $prefix . '_PASSWORD') ?: '', [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        ]);
        $schema = getenv('CRUD_TEST_' . $prefix . '_SCHEMA') ?: match ($driver) {
            'pgsql' => 'public', 'sqlsrv' => 'dbo', default => $pdo->query('SELECT DATABASE()')->fetchColumn(),
        };
        $name = 'crud_fixture_' . bin2hex(random_bytes(4));
        $parent = $name . '_parent';
        $quote = static fn ($value) => match ($driver) {
            'mysql', 'mariadb' => chr(96) . str_replace(chr(96), chr(96) . chr(96), $value) . chr(96),
            'sqlsrv' => '[' . str_replace(']', ']]', $value) . ']',
            default => '"' . str_replace('"', '""', $value) . '"',
        };
        $qualified = $quote($schema) . '.' . $quote($name);
        $parentQualified = $quote($schema) . '.' . $quote($parent);
        $identity = match ($driver) {
            'pgsql' => 'BIGINT GENERATED BY DEFAULT AS IDENTITY',
            'sqlsrv' => 'BIGINT IDENTITY(1,1)',
            default => 'BIGINT AUTO_INCREMENT',
        };
        $pdo->exec("CREATE TABLE $parentQualified (id INT PRIMARY KEY)");
        try {
            $pdo->exec("CREATE TABLE $qualified (id $identity PRIMARY KEY, email VARCHAR(120) NOT NULL UNIQUE, parent_id INT NULL, amount DECIMAL(12,2) NOT NULL DEFAULT 0, FOREIGN KEY (parent_id) REFERENCES $parentQualified (id))");
            try {
                $executor = new class($pdo) implements QueryExecutor {
                    public function __construct(private PDO $pdo) {}
                    public function select(string $connection, string $sql, array $bindings = []): array
                    {
                        $statement = $this->pdo->prepare($sql);
                        $statement->execute($bindings);
                        return $statement->fetchAll(PDO::FETCH_ASSOC);
                    }
                };
                $inspector = new SchemaInspector($executor);
                self::assertContains($name, $inspector->tables('test', $driver, $schema));
                $table = $inspector->inspect($name, 'test', $driver, $schema);
                self::assertSame('id', $table->key()->name);
                self::assertTrue($table->key()->identity);
                self::assertSame(120, $table->column('email')->length);
                self::assertSame('decimal:2', $table->column('amount')->cast());
                self::assertContains(['email'], $table->uniqueKeys);
                self::assertSame(['parent_id'], $table->foreignKeys[0]['columns']);
                self::assertSame($parent, $table->foreignKeys[0]['table']);
            } finally {
                $pdo->exec("DROP TABLE $qualified");
            }
        } finally {
            $pdo->exec("DROP TABLE $parentQualified");
        }
    }
}
